[custom]

;设置规则标志位
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaIp.list
;ruleset=🚀 复写选中,https://github.com/fastcoderspencer/MerlinClash_subconverter/raw/main/subconverter/rules/ACL4SSR/Clash/Ruleset/DiyStrategy.list
ruleset=🚀 复写选中,https://cdn.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter/subconverter/rules/ACL4SSR/Clash/Ruleset/DiyStrategy.list
;🦹‍♂️ DiyStrategy
;PayPal
ruleset=💰 PayPal,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PayPal/PayPal.list
;👽 Claude
ruleset=👽 Claude,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.list
;OpenAI、;♊ Gemini;
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.list
ruleset=⌨️ Cursor,https://cdn.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter/subconverter/rules/ACL4SSR/Clash/Ruleset/Cursor.list
ruleset=⌨️ Cursor,https://cdn.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter/subconverter/rules/ACL4SSR/Clash/Ruleset/Trae.list

ruleset=🌐 Dia,https://cdn.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter/subconverter/rules/ACL4SSR/Clash/Ruleset/Dia.list

;UltraPayGo
;ruleset=📱 UltraPayGo,https://cdn.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter@main/subconverter/rules/ACL4SSR/Clash/Ruleset/UltraPayGo.list
;Github
ruleset=🐱 GitHub,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Github.list
;Microsoft
ruleset=🧩 微软服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
ruleset=🧩 微软服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
ruleset=🧩 微软服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.list
;Youtube
ruleset=📹 YouTube,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/YouTube.list
;Google
ruleset=🔍 Google,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🔍 Google,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🔍 Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleFCM.list
ruleset=🔍 Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🔍 Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleCN.list
ruleset=🔍 Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Google.list
;
ruleset=🍎 苹果服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
ruleset=🎵 TikTok,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.list
ruleset=📲 Telegram,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
ruleset=🎮 游戏平台,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.list
ruleset=🎥 奈飞迪士尼,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Netflix.list
ruleset=🎥 奈飞迪士尼,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/NetflixIP.list
ruleset=🎥 奈飞迪士尼,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DisneyPlus.list
ruleset=🇨🇳 国内媒体,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaMedia.list
ruleset=🇨🇳 国内媒体,https://cdn.jsdelivr.net/gh/chinnsenn/ClashCustomRule@master/deprecated/weibo.list
ruleset=🌍 国外媒体,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
ruleset=🇺🇳 国外网站,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list
ruleset=🇺🇳 国外网站,https://cdn.jsdelivr.net/gh/chinnsenn/ClashCustomRule@master/deprecated/proxies.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🚀 手动切换`[]♻️ 延迟最低`[]♻️ 专线最低`[]DIRECT`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`[]🇰🇷 韩国节点组
; custom_proxy_group=🚀 节点选择`select`[]🚀 手动切换`[]♻️ 延迟最低`[]DIRECT`[]🇯🇵 日本节点组-Pick`[]🇬🇧 英国节点组`[]🇰🇷 韩国节点组
custom_proxy_group=🚀 手动切换`select`.*`[]DIRECT
custom_proxy_group=🚀 复写选中`select`.*`[]DIRECT
custom_proxy_group=🚀 复写选中2`select`.*`[]DIRECT
custom_proxy_group=🚀 复写选中3`select`.*`[]DIRECT
custom_proxy_group=🌊 大流量手动切换`select`[]🇺🇳 大流量节点组`[]🇺🇳 大流量节点组-香港`[]🇺🇳 大流量节点组-台湾`[]🇺🇳 大流量节点组-新加坡`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=💡 固定IP特殊服务`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
; custom_proxy_group=🦹‍♂️ DiyStrategy`select`.*
custom_proxy_group=💰 PayPal`select`(美|美国|USA|US|United States)`[]DIRECT
; custom_proxy_group=📱 UltraPayGo`select`.*`[]DIRECT
custom_proxy_group=🤖 AI服务`select`[]💡 固定IP特殊服务`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=👽 Claude`select`[]💡 固定IP特殊服务`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=⌨️ Cursor`select`[]💡 固定IP特殊服务`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🌐 Dia`select`[]💡 固定IP特殊服务`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🐱 GitHub`select`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🔍 Google`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🎵 TikTok`select`[]💡 固定IP特殊服务`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*
custom_proxy_group=🧩 微软服务`select`[]DIRECT`[]💡 固定IP特殊服务`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🎥 奈飞迪士尼`select`[]🌊 大流量手动切换`[]🇺🇳 大流量节点组-香港`[]🇺🇳 大流量节点组-台湾`[]🇺🇳 大流量节点组-新加坡`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🇺🇳 国外网站`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*`[]DIRECT
custom_proxy_group=🇨🇳 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🌊 大流量手动切换`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇳 大流量节点组`[]🇺🇳 大流量节点组-香港`[]🇺🇳 大流量节点组-台湾`[]🇺🇳 大流量节点组-新加坡`[]🇭🇰 香港节点组-Pick`[]🇸🇬 新加坡节点组-Pick`[]🇺🇲 美国节点组-Pick`[]🇨🇳 台湾节点组-Pick`[]🇯🇵 日本节点组-Pick`.*


;test-group
custom_proxy_group=♻️ 延迟最低`url-test`(^(?!.*(IPLC|AGA|IEPL|IPEL)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 专线最低`url-test`(IPLC|AGA|IEPL|IPEL|专线)`http://www.gstatic.com/generate_204`300,,50
;url-test
custom_proxy_group=🇺🇳 大流量节点组`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急|新疆|亚马逊|谷歌云)).*(香港|Hong Kong|新加坡|Singapore|台湾))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇳 大流量节点组-香港`url-test`(.*(香港 01 2|香港 02 2|香港 03 2|香港 04 2|香港 05 2|香港 06 2))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇳 大流量节点组-台湾`url-test`(.*(台湾 01 2|台湾 02 2))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇳 大流量节点组-新加坡`url-test`(.*(新加坡 01 2|新加坡 02 2|新加坡 03 2|新加坡 04 2))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇭🇰 香港节点组-Pick`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急|亚马逊|谷歌云)).*(香港|Hong Kong))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇸🇬 新加坡节点组-Pick`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急|新疆|亚马逊|谷歌云)).*(新加坡|Singapore))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇲 美国节点组-Pick`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急|亚马逊|谷歌云)).*(美国|United States))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇯🇵 日本节点组-Pick`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急|亚马逊|谷歌云)).*(日本))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点组-Pick`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急|亚马逊|谷歌云)).*(台湾|Taiwan))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇰🇷 韩国节点组`url-test`(^(?!.*(IPLC|AGA|IEPL|广港|应急)).*(KR|Korea|KOR|首尔|韩|韓))`http://www.gstatic.com/generate_204`300,,100


;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

; exclude_remarks=(IPV6|重置|流量|用户|本站|漏洞|永久虚通路|车|邀|免翻|邀请|eevpn|域名|机场|刷新|到期|套餐|官网|更多|关注|临时)

;luck

;地址
;https://raw.githubusercontent.com/fastcoderspencer/MerlinClash_subconverter/main/subconverter/ruleconfig/diy23.ini
;https://cdn.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter@main/subconverter/ruleconfig/diy23.ini
;https://purge.jsdelivr.net/gh/fastcoderspencer/MerlinClash_subconverter@main/subconverter/ruleconfig/diy23.ini
